lyfe/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :teaser
  resources :early_registrants

  root 'teaser#index'
end

lyfe/app/models/early_registrant.rb
class EarlyRegistrant < ActiveRecord::Base
  
end

lyfe/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

lyfe/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lyfe/app/controllers/early_registrants_controller.rb
class EarlyRegistrantsController < ApplicationController
  before_action :parse_parameters, only: [:create]
  
  attr_accessor :parameters

  def create
    er = EarlyRegistrant.new(parameters)
    res = er.save

    message = res ? {success: 'Registration Saved!'} : {error: 'Unable to save registration'}
    redirect_to teaser_index_path, flash: message
  end

  private

  def parse_parameters
    full_name = "#{params[:name]} #{params[:surname]}"
    @parameters = {full_name: full_name, email: params[:email]}
  end
end

lyfe/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

lyfe/app/controllers/teaser_controller.rb
class TeaserController < ApplicationController
  def index
  end
end

lyfe/app/helpers/application_helper.rb
module ApplicationHelper
end

lyfe/app/helpers/early_registrants_helper.rb
module EarlyRegistrantsHelper
end

lyfe/app/helpers/site_helper.rb
module SiteHelper
end

lyfe/app/helpers/teaser_helper.rb
module TeaserHelper
end

lyfe/app/views/layouts/application.slim
doctype html
html
  head
    title Lyfe
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no'
  body
    = yield

lyfe/app/views/site/index.slim
p
  | trololololo

lyfe/app/views/teaser/index.slim
#teaser-main.teaser-bg.vertical-center
  .container
    .row
      .col-md-6
        .row
          = image_tag 'generic/icons/lyfe-logo.svg', class: 'img-responsive mlauto mrauto' 
      .col-md-6.text-center
          .row
            .text-white.fs88 
              strong Coming Soon
          .row.mr10.ml10
            .text-orange.fs40.mb30 
              strong We have something special for you to be inspired for.
          .row.mr10.ml10
            .text-white.fs16.mb30 Enter your email address to be the first to know when we launch it.
          .row.mr10.ml10
            .form-container.pt25.pr25.pl25.pb10
              = form_for :job, url: early_registrants_path, :html => {'data-toggle' => 'validator', 'role' => 'form' } do |f|
                .form-group
                  input type="text" class="form-control flat ht50" id="name" name='name' placeholder="Name" required=true
                  .help-block.with-errors.text-left
                .form-group
                  input type="text" class="form-control flat ht50" id="surname" name='surname' placeholder="Surname" required=true
                  .help-block.with-errors.text-left
                .form-group
                  input type="email" class="form-control flat ht50" id="email" name='email' placeholder="Email" required=true
                  .help-block.with-errors.text-left
                button type="submit" class="btn btn-orange flat ht50 wt100p mb10 fs20 fw700" Inspire Me